blank_issues_enabled: false
contact_links:
  - name: Home Assistant Community Forum Thread
    url: https://community.home-assistant.io/t/hacs-nen-energy-italian-gas-electricity-integration/1007138
    about: For general questions, support, and community discussions about NeN Energy integration.
